// <auto-generated />
using ApiSimulador.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSimulador.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ApiSimulador.Domain.Entities.Produtos.Produto", b =>
                {
                    b.Property<long>("CoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CO_PRODUTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NO_PRODUTO");

                    b.Property<int>("PrazoMaximoMeses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRAZO_MAXIMO_MESES");

                    b.Property<decimal>("TaxaJurosAnual")
                        .HasColumnType("TEXT")
                        .HasColumnName("PC_TAXA_JUROS_ANUAL");

                    b.HasKey("CoProduto");

                    b.ToTable("PRODUTO");
                });
#pragma warning restore 612, 618
        }
    }
}
